### PR TITLE
feat(ComboBox): code changes to show typeahead sort of text of options value in input box

### PR DESCRIPTION
**Pull request by jpuri**
Code changes look good enough to be merged...

### CODE REVIEW

**Comment by nikgraf** [comment]
@jpuri I found a few questions/issues we probably should fix first:

1. I typing in "Te". While "Te" is in the originally provided list it is not shown as an Option.

2. When typing in "TE" (uppercased) the background characters are lowercase in grey & do not properly overlap.

3. When clicking on the input I instantly see the first suggestion. When I hit the backspace key it is removed instantly.

4. Why did you call it pseudoInput? With pseudo in the context of HTML I associate [pseudo classes](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes) in CSS. Why not call it just `hint`? btw I didn't come up with this name. I noticed typeahead uses it as class name on their hidden input.

**Comment by jpuri** [comment]
Hey Nik,

Thanks a lot for these detailed feedback :smile:

**Comment by jpuri** [comment]
I have added t this branch 2 commit, that is small refactoring which was pending for Rating component.

**Comment by jpuri** [comment]
That's good idea I think, having props everywhere.

**Pull request merged**
