### PR TITLE
chore(dependencies): upgrade react, react-router, and jest

### PR DESCRIPTION
**Pull request by mcbryant**
The goal of this patch is to resolve warnings present when using Belle in a React 15.x codebase.
This patch should not change the behaviour of Belle.

Details:

 - tests, docs, and examples: upgraded to React 15.x
 - docs: upgraded to React Router 2.5.2 for compatibility with React 15.x
   (see https://github.com/ReactTraining/react-router/issues/3695)
 - src, tests, docs, and examples: fixed various warnings introduced throughout React 15.x
 - tests: upgraded Jest for compatibility with Node 6 (https://github.com/facebook/jest/issues/1088)

Testing:

 - verified that there were no React-related warnings in tests, docs, and examples
 - browsed docs and examples in Chrome and FF

### CODE REVIEW

**Comment by mcbryant** [comment]
Note: This can be applied to the `v3` branch with small changes. I'll make a PR once this is merged.

**Comment by nikgraf** [comment]
@mcbryant I believe from all I learned v3 will be started over in a few months.

After this awesome contribution I will give you commit writes. Interested to contribute more?

**Comment by mcbryant** [comment]
I'm definitely interested! Thank you for your consideration, and I'll see what I can do!

**Comment by nikgraf** [comment]
@mcbryant feel free to ping me anytime on Twitter or here. I have some ideas, but too little time 😄

**Pull request merged**
