### PR TITLE
Combobox changes

### PR DESCRIPTION
**Pull request by jpuri**
Hey @nikgraf , does this name 'onInputMatch' for the new api method looks good ?

### CODE REVIEW

**Comment by nikgraf** [comment]
Changes look good.

I researched a bit more regarding ComboBox and as defined by the W3C consortium the combobox is a subclass of a select tag.

"A presentation of a select; usually similar to a textbox where users can type ahead to select an option, or type to enter arbitrary text as a new item in the list. See related listbox."
http://www.w3.org/TR/wai-aria/complete#combobox

To me this implies it should behave like one. Meaning the onUpdate should only be triggered in case an exact match happened. Unfortunately this will break our existing API, but I think it's better to do it now than later.

You might wonder what about the other use-cases when ComboBox is used like a Google. This is already possible by providing `inputProps.onChange` and listen to this one. We could add `inputProps.onUpdate` but I don't feel it's necessary.

@jpuri What do you think?

**Comment by jpuri** [comment]
Nice research Nik,

We have components which are like blend of 2 others like rating something between a button and a form component.

This is how W3C definition goes - "A presentation of a select; usually similar to a textbox where users can type ahead to select an option, or type to enter arbitrary text as a new item in the list. See related listbox. combobox is the combined presentation of a single line textfield with a listbox popup. The combobox may be editable. Typically editable combo boxes are used for autocomplete behavior, and authors SHOULD set aria-autocomplete attribute on the textfield."

Its actually blend of select and input, this makes tough to decide the api. I do not want to go by the name 'ComboBox' or definition to design api, but want to create something that would fit need of web development and users of belle as of now - its our chance to do it better than w3c :smile: 

I think best way out is have 2 methods:
1. Triggered for exact match
2. Trigger for every change - for this we can not depend on onChange of React's ```<input>``` as it will not be triggered when user selects an option.

We can give any names in our api to these methods.

You can check this events in typeahead.js: https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#custom-events

It has events for both input and select. I do not mind breaking the api, but what new we design should be great.

**Comment by jpuri** [comment]
How about methods names like 
1. onUpdate - for any change
2. onSelect - for exact match

**Comment by jpuri** [comment]
We might need to rethink upon 'onInputMatch' implemented as of now, the use case I see problematic is if suppose we have 4 options like 
1. test
2. testing
3. testing12
4. testing12345

As soon as user types 'test' function 'onInputMatch' will be called. Might be user intended to type 'test' and then select 'testing12345'.

I think like typeadhead.js we call these callbacks only if user selects or autocompletes using hint one of the options. User may type whole values but then its developers to handle these scenarios in 'onUpdate'.

**Comment by nikgraf** [comment]
Use cases we want to cover:

a. A field where the users needs to select a valid options (Pick a Country)
b. A search field with suggestions like google (just as help, but doesn't effect the output)
c. A search field where in case of a perfect match a redirect to the entry happens, otherwise a search page with alternative pages open
d. A search field where in case of a select from an option a redirect to the entry happens, otherwise a search page with possible entries open

Proposal 1
----------

onUpdate (fires whenever the input changes)
onExactMatch (fires when an option has chosen or the input match happend)

a.

```
<ComboBox onExactMatch={ (event) => { _chooseOption(event.identifier) }}>
  <Option value="Alaska" identifier={ 1 }>Alaska</Option>
  <Option value="California"  identifier={ 2 }>California</Option>
</ComboBox>
```

b.

```
<ComboBox onUpdate={ (event) => { _updateSearchTerm(event.value) }}>
  <Option value="Alaska">Alaska</Option>
  <Option value="California">California</Option>
</ComboBox>
```

c.

no idea, but probably super complex? We would somehow need to know which fires first and then sync those events.

d.

no idea, but probably super complex? We could add another method to only fire when something is selected, but it doesn't help

Proposal 2
----------

onUpdate (fires whenever a select/exact match happens)
inputProps.onUpdate (fires when input changes including select)

a.

```
<ComboBox onUpdate={ (event) => { _chooseOption(event.identifier) }}>
  <Option value="Alaska" identifier={ 1 }>Alaska</Option>
  <Option value="California"  identifier={ 2 }>California</Option>
</ComboBox>
```

b.

```
<ComboBox inputProps={{ onUpdate: (event) => { _updateSearchTerm(event.value) }}}>
  <Option value="Alaska">Alaska</Option>
  <Option value="California">California</Option>
</ComboBox>
```

c.

no idea, but probably super complex? We would somehow need to know which fires first and then sync those events.

d.

no idea, but probably super complex? We could add another method to only fire when something is selected, but it doesn't help


Proposal 3
----------

onUpdate (fires whenever the input changes, in case of a perfect match the optionMatch is set to true, in case an option has been selected optionSelect is set to true)

```
onUpdate({
  value: 'weee',
  identifier: 1
  optionMatch: true/false, (not sure about the name here)
  optionSelect: true/false (not sure about the name here)
})
```

a.

```
<ComboBox onUpdate={ (event) => { if (event.optionMatch) { _chooseOption(event.identifier) }}}>
  <Option value="Alaska" identifier={ 1 }>Alaska</Option>
  <Option value="California"  identifier={ 2 }>California</Option>
</ComboBox>
```

b.

```
<ComboBox onUpdate={ (event) => { _updateSearchTerm(event.value) }}>
  <Option value="Alaska">Alaska</Option>
  <Option value="California">California</Option>
</ComboBox>
```

c.

```
<ComboBox onUpdate={ (event) => {
    if (event.optionMatch) {
      _redirectToEntry(event.identifier)
    } else {
      _updateSearchTerm(event.value)
    }}}>
  <Option value="Alaska" identifier={ 1 }>Alaska</Option>
  <Option value="California"  identifier={ 2 }>California</Option>
</ComboBox>
```

d.

```
<ComboBox onUpdate={ (event) => {
    if (event.optionSelect) {
      _redirectToEntry(event.identifier)
    } else {
      _updateSearchTerm(event.value)
    }}}>
  <Option value="Alaska" identifier={ 1 }>Alaska</Option>
  <Option value="California" identifier={ 2 }>California</Option>
</ComboBox>
```

How do you feel about these proposal? Which one do you like more? Which one you don't? Feel free to add use-cases or other proposals. @jpuri

**Comment by jpuri** [comment]
Hey Nik,

Proposal-3 looks useful, very nice idea :+1:

**Comment by nikgraf** [comment]
@jpuri hey :smile:

I like it the most as well. It doesn't break the API, but opens up new opportunities. The only downside is that for the `a` use-case it's a bit more complicated then it needs to be. But that's fine :smile: 

What do you think about the names `optionMatch` & `optionSelect`? Do you have better ideas?

**Comment by jpuri** [comment]
Hey Nik,

These names looks fine. For use case (a) we can still add callback for case when user selects option (in addition to these params).

**Pull request merged**
