### PR TITLE
fix: poor performance of controlled components in docs due to repeate…

### PR DESCRIPTION
**Pull request by jpuri**
Hey @nikgraf ,

Can you check this change locally before u merge, this has definitely fixed the performance issue with TextInput.

But somehow I do not see highlighting in my local, with or without this fix (although http://nikgraf.github.io/belle/#/ has code highlighting). Can you confirm at your end if highlighting is intact after this change.

### CODE REVIEW

**Comment by nikgraf** [comment]
I'm so glad you identified that issue. Sadly this will prevent the highlighting on the page. It never worked on development, because the css file is not available.

I will check later today, but it should be possible to render the highlighting code component only once.

**Comment by jpuri** [comment]
Hey nik
R u sure, it may just work as highlight.js is still called when code
component is mount. I just removed call from update.

**Comment by jpuri** [comment]
I expect the fix to work coz in dev environment also the highlight.js classes are getting applide in code block. Its just that css is not there.

**Comment by nikgraf** [comment]
@jpuri I made a change. What do you think about this version?

**Comment by jpuri** [comment]
Hey Nik,

+1, I was also thinking of doing it this way. Though its very less probable that value param will change dynamically. But still I think this would be better fix, in fact I can revert mine. Let me do that.

That makes me thing how careful one should be to optimize render for controlled components.

**Pull request merged**
