### PR TITLE
Add CSS transform scale example to Toggle documentation

### PR DESCRIPTION
**Pull request by iansinnott**
Added example using CSS `transform: scale(...)` to resize the Toggle component.

### CODE REVIEW

**Comment by iansinnott** [comment]
It might be useful to add a note somewhere more general in the docs to remind people about CSS transforms. It's one of those things that people generally don't use very often so we tend to forget.

Docs: [CSS Transforms][]

[CSS Transforms]: https://developer.mozilla.org/en-US/docs/Web/CSS/transform

**Comment by jpuri** [comment]
Hey @iansinnott , thanks a lot. We will soon check this out.

**Comment by jpuri** [comment]
Thanks a lot @iansinnott

**Comment by iansinnott** [comment]
Happy to help. When I first found Belle I completely forgot about transforms and this would have been exactly what I needed :grin:

**Pull request merged**
