### PR TITLE
Fix `Unknown prop `allowNewLine` on <textarea>`

### LINKED ISSUE #321: Unknown prop `allowNewLine` on <textarea>
Hi!

Nice work!

A little problem (non blocking), React throw warning when I'm using TextInput component:
```
warning.js:44 Warning: Unknown prop `allowNewLine` on <textarea> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in textarea (created by TextInput)
    in TextInput (created by Form)
    in form (created by Form)
    in div (created by Card)
    in Card (created by Form)
    in Form (created by Connect(Form))
    in Connect(Form) (created by Header)
    in header (created by Header)
    in Header (created by Connect(Header))
    in Connect(Header) (created by MainApp)
    in div (created by MainApp)
    in MainApp
    in div (created by AppRoot)
    in Provider (created by AppRoot)
    in div (created by AppRoot)
    in AppRoot
```

### PR DESCRIPTION
**Pull request by mafzst**
Fix #321

### CODE REVIEW

**Comment by mcbryant** [comment]
This fixes `allowNewLine` on `<textarea />`, but similar issues also exist for other properties in other components. I gave the other properties a shot [across the repo](https://github.com/nikgraf/belle/pull/323).

**Comment by mafzst** [comment]
@mcbryant Nice! I close this one in favor of yours (#323)

**Comment by nikgraf** [comment]
thx for your awesome work @mafzst & @mcbryant

**Comment by nikgraf** [comment]
@mafzst interested to contribute more? I could provide you with collaborator right …

**Comment by mafzst** [comment]
@nikgraf Thank for your consideration. But I don't think I have enough time to contribute efficiently to your package.
When I find something weird I try to fix it and I create a PR. But I have no time to develop feature and enhancements

**Comment by nikgraf** [comment]
Thx again for your fix!

**Pull request closed without merging**
