### PR TITLE
Remove Reactiflux reference

### PR DESCRIPTION
**Pull request by vcarl**
I'm one of the mods of Reactiflux, excess channels has been brought up as an issue for new users (partly because Discord is opt-out instead of opt-in). I'd like to remove the Belle channel since it hasn't had any activity in a few weeks.

### CODE REVIEW

**Comment by nikgraf** [comment]
hmmm, yeah activity dropped a lot after moving from Slack to Reactiflux. Any suggestion where to guide people for questions & discussions?

**Comment by vcarl** [comment]
Gitter or a channel on Freenode are both good options.

**Comment by nikgraf** [comment]
thx for the advice @vcarl

**Comment by vcarl** [comment]
Can also point people to the general or need-help channel, if traffic picks up can make the channel again. I don't want to imply that Discord isn't for library chatter, it just has really bad discoverability.

**Comment by nikgraf** [comment]
Have you guys considered moving to another tool? Maybe https://chatgrape.com/ ??? /cc @kof

**Comment by kof** [comment]
Reactiflux moved from slack recently, I doubt they want to move again. Also chatgrape hasn't been nested with 10k sized communities yet.

**Pull request merged**
